# Dockerfile
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=reddit_user
ENV POSTGRES_PASSWORD=reddit_pass
ENV POSTGRES_DB=reddit_db

# Expose default PostgreSQL port
EXPOSE 5432
